#!/bin/sh
# Wait for all other services to be up.
for service in /etc/service/*; do
    if [ ! -f $service/down ]; then
        s6-svwait -u $service
    fi
done

# Change to the user working directory.
cd $(cat /run/pwd)

# Execute the user command.
IFS=$'\n'
exec s6-setsid -g -q $(cat /run/cmdline)
