#!/bin/sh
if [ -f /srv/seafile-server/runtime/seahub.pid ]; then
    rm /srv/seafile-server/runtime/seahub.pid
fi

exec gunicorn seahub.wsgi:application -c /srv/seafile-server/runtime/seahub.conf -b 127.0.0.1:8000 --enable-stdio-inheritance --capture-output
